version: '3.8'
services:
  controller:
    build: ./backend
    command: python main.py
    ports:
      - "8000:8000"
    networks:
      - amanq-net

  server1:
    build: ./backend
    command: python agent.py
    environment:
      - SERVER_NAME=S1
      - CONTROLLER_IP=controller
    depends_on:
      - controller
    networks:
      - amanq-net

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - amanq-net

networks:
  amanq-net:
    driver: bridge